version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  app:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:80"
    depends_on:
      - elasticsearch
    restart: always


  data_loader:
    build:
      context: ./es_loader
    container_name: es_data_loader
    depends_on:
      - elasticsearch
    command: ["python", "/app/load_data.py"]
    restart: on-failure

volumes:
  esdata:
    driver: local
